spring.application.name=flashEngine

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/flashengine
spring.datasource.username=postgres
spring.datasource.password=Abhi@1289
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379

#Instruct spring boot to wait active requests to complete before shutting down
server.shutdown=graceful

#time limit allowed for active requests to complete before shutting down
spring.lifecycle.timeout-per-shutdown-phase=30s

# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Disable default requeueing
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Enable retry state management inside the listener container
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms